create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 120),
  email text check (email is null or char_length(email) <= 180),
  phone text not null check (char_length(phone) <= 40),
  service text not null check (char_length(service) <= 120),
  message text not null check (char_length(message) <= 2000),
  page_url text check (page_url is null or char_length(page_url) <= 500),
  user_agent text check (user_agent is null or char_length(user_agent) <= 500),
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Anyone can submit contact messages" on public.contact_messages;

create policy "Anyone can submit contact messages"
  on public.contact_messages
  for insert
  to anon
  with check (true);

grant insert on public.contact_messages to anon;
grant usage on sequence public.contact_messages_id_seq to anon;
grant all on public.contact_messages to service_role;
